### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by blogh** [gooplancton/codecrafters-kafka-rust#1]
Hi,

I came across your code in codecrafters.
I am a beginner and I think your code is very cool, there is so much to learn here :)

Thanks !

**Comment by gooplancton** [comment]
Hi @blogh 😊 
Glad you found my implementation interesting! I haven't been very active on codecrafters recently as I've just moved to China and I'm still getting used to the new environment 😅.
I've written 3 Medium articles about another toy project of mine if you're interested. I think you could learn a thing or two from them 😁.

https://medium.com/@leonardo_santangelo/implementing-an-irc-server-from-scratch-in-rust-d387e6850b6e

Thank you again for the appreciation and good luck in your Rust learning journey!
